SELECT * FROM CompetitionAdmin;
SELECT * FROM League;
SELECT * FROM Team;
SELECT * FROM TeamManagement;
SELECT * FROM Player;
SELECT * FROM Referee;
SELECT * FROM Game;
SELECT * FROM GamePlayerStats;
SELECT * FROM GameTeamStats;
